/**
 * This file was automatically generated by Strapi.
 * Any modifications made will be discarded.
 */
import cmsAnalyzer from "@exfabrica/strapi-plugin-awesome-seo/strapi-admin";
import strapiCloud from "@strapi/plugin-cloud/strapi-admin";
import i18N from "@strapi/plugin-i18n/strapi-admin";
import usersPermissions from "@strapi/plugin-users-permissions/strapi-admin";
import sitemap from "strapi-plugin-sitemap/strapi-admin";
import { renderAdmin } from "@strapi/strapi/admin";

renderAdmin(document.getElementById("strapi"), {
  plugins: {
    "cms-analyzer": cmsAnalyzer,
    "strapi-cloud": strapiCloud,
    i18n: i18N,
    "users-permissions": usersPermissions,
    sitemap: sitemap,
  },
});
